$filePath = "C:\Users\User\.kiro\CodingCamp-18May26-Raka\.kiro\specs\todo-life-dashboard\requirements.md"

$lines = @(
"# Requirements Document",
"",
"## Introduction",
"",
"The To-Do Life Dashboard is a client-side, single-page web application that serves as a personal homepage dashboard. It helps users organize their day by displaying the current time and date, a personalized greeting, a configurable Pomodoro focus timer, a task management list, and a quick-access links panel. The application runs entirely in the browser using HTML, CSS, and Vanilla JavaScript, with all user data persisted via the browser's LocalStorage API. It supports both light and dark visual themes and is compatible with Chrome, Firefox, Edge, and Safari.",
"",
"## Glossary",
"",
"- **Dashboard**: The main single-page web application interface containing all widgets.",
"- **Greeting_Widget**: The UI component that displays the current time, date, and a personalized greeting message.",
"- **Focus_Timer**: The Pomodoro-style countdown timer widget.",
"- **Task_List**: The UI component that manages the user's to-do items.",
"- **Task**: A single to-do item with a title, completion status, and unique identifier.",
"- **Quick_Links**: The UI component that displays user-defined shortcut buttons to external websites.",
"- **Link**: A single quick-access entry containing a label and a URL.",
"- **LocalStorage**: The browser's built-in client-side key-value storage API.",
"- **Theme**: The visual color scheme of the Dashboard, either `"light`" or `"dark`".",
"- **Pomodoro_Duration**: The configurable countdown duration for the Focus_Timer, defaulting to 25 minutes.",
"- **User_Name**: The custom name entered by the user, displayed in the greeting message.",
"",
"---",
"",
"## Requirements",
"",
"### Requirement 1: Display Current Time and Date",
"",
"**User Story:** As a user, I want to see the current time and date on the dashboard, so that I can stay aware of the time without switching tabs.",
"",
"#### Acceptance Criteria",
"",
"1. THE Greeting_Widget SHALL display the current time in HH:MM:SS format using the user's local system timezone.",
"2. THE Greeting_Widget SHALL display the current date in the format: ``<Day of Week>, <DD> <Month Name> <YYYY>`` (e.g., Monday, 26 May 2025).",
"3. WHEN the Dashboard is opened, THE Greeting_Widget SHALL immediately display the current time and date without requiring any user interaction.",
"4. WHILE the Dashboard is open, THE Greeting_Widget SHALL update the displayed time every second, such that the seconds value increments by 1 each update.",
"",
"---",
"",
"### Requirement 2: Personalized Greeting",
"",
"**User Story:** As a user, I want to see a greeting that uses my name and reflects the time of day, so that the dashboard feels personal and contextual.",
"",
"#### Acceptance Criteria",
"",
"1. WHEN the current hour is between 05:00 and 11:59, THE Greeting_Widget SHALL display the message `"Good Morning, [User_Name]!`".",
"2. WHEN the current hour is between 12:00 and 17:59, THE Greeting_Widget SHALL display the message `"Good Afternoon, [User_Name]!`".",
"3. WHEN the current hour is between 18:00 and 21:59, THE Greeting_Widget SHALL display the message `"Good Evening, [User_Name]!`".",
"4. WHEN the current hour is between 22:00 and 04:59, THE Greeting_Widget SHALL display the message `"Good Night, [User_Name]!`".",
"5. WHEN no User_Name has been saved, or the stored value is unreadable or corrupted, THE Greeting_Widget SHALL substitute User_Name with the placeholder `"there`".",
"6. WHEN the user submits a name via the name input field, THE Dashboard SHALL trim leading and trailing whitespace from the input; IF the trimmed value is between 1 and 50 characters inclusive, THE Dashboard SHALL save the trimmed User_Name to LocalStorage and update the greeting within 1 second.",
"7. IF the user submits an empty string or a whitespace-only string as the User_Name, THEN THE Dashboard SHALL retain the previously saved User_Name without modification.",
"",
"---",
"",
"### Requirement 3: Focus Timer (Pomodoro)",
"",
"**User Story:** As a user, I want a countdown timer I can start, stop, and reset, so that I can manage focused work sessions using the Pomodoro technique.",
"",
"#### Acceptance Criteria",
"",
"1. THE Focus_Timer SHALL display the remaining time in MM:SS format.",
"2. WHILE the Focus_Timer is in a stopped or reset state, THE Focus_Timer SHALL display the full Pomodoro_Duration.",
"3. WHEN the user clicks the Start button, THE Focus_Timer SHALL begin counting down one second per second.",
"4. WHEN the user clicks the Stop button, THE Focus_Timer SHALL pause the countdown and retain the remaining time.",
"5. WHEN the user clicks the Reset button, THE Focus_Timer SHALL stop the countdown and restore the display to the full Pomodoro_Duration.",
"6. WHEN the countdown reaches 00:00, THE Focus_Timer SHALL stop automatically, play an audio signal, and display a visual completion indicator.",
"7. WHEN the countdown reaches 00:00, THE Focus_Timer SHALL disable the Start button until the user clicks the Reset button.",
"8. WHEN the user saves a new Pomodoro_Duration by clicking a dedicated Save button or pressing Enter in the duration input field, THE Focus_Timer SHALL validate that the value is a positive integer between 1 and 60 (inclusive).",
"9. IF the user enters a Pomodoro_Duration outside the range of 1 to 60, THEN THE Focus_Timer SHALL reject the input and retain the previously saved Pomodoro_Duration.",
"10. WHEN a valid Pomodoro_Duration is saved, THE Dashboard SHALL persist the value to LocalStorage and reset the Focus_Timer to the new duration.",
"",
"---",
"",
"### Requirement 4: Task Management",
"",
"**User Story:** As a user, I want to add, edit, complete, and delete tasks, so that I can track what I need to accomplish during the day.",
"",
"#### Acceptance Criteria",
"",
"1. WHEN the user submits a non-empty task title (up to 200 characters) via the task input field, THE Task_List SHALL add a new Task with a unique identifier, the provided title, and a completion status of false.",
"2. IF the user submits an empty string as a task title, THEN THE Task_List SHALL not add a new Task and SHALL display an inline validation message; the validation message SHALL be cleared on the next valid submission attempt.",
"3. WHEN a Task is added, edited, or deleted, THE Dashboard SHALL persist the updated Task_List to LocalStorage.",
"4. WHEN the user clicks the complete toggle on a Task, THE Task_List SHALL update the Task's completion status to true and apply a visual strikethrough style to the task title.",
"5. WHEN the user clicks the complete toggle on a completed Task, THE Task_List SHALL update the Task's completion status to false and remove the strikethrough style.",
"6. WHEN the user clicks the edit button on a Task, THE Task_List SHALL display an inline editable input pre-filled with the Task's current title.",
"7. WHEN the user confirms an edit by pressing Enter or clicking a save button with a non-empty title, THE Task_List SHALL update the Task's title and exit edit mode.",
"8. IF the user confirms an edit by pressing Enter or clicking a save button with an empty title, THEN THE Task_List SHALL retain the Task's original title and exit edit mode without modifying the task.",
"9. WHEN the user presses Escape while in edit mode, THE Task_List SHALL discard any changes and exit edit mode, restoring the original title.",
"10. WHEN the user clicks the delete button on a Task, THE Task_List SHALL remove the Task from the list and update LocalStorage.",
"11. WHEN the Dashboard loads, THE Task_List SHALL restore all previously saved Tasks from LocalStorage.",
"12. IF LocalStorage data for the Task_List is unreadable or corrupted on load, THEN THE Task_List SHALL initialize with an empty list and not throw an unhandled error.",
"",
"---",
"",
"### Requirement 5: Quick Links",
"",
"**User Story:** As a user, I want to save and access my favorite website links from the dashboard, so that I can navigate to them quickly without typing URLs.",
"",
"#### Acceptance Criteria",
"",
"1. WHEN the user submits a non-empty label (up to 100 characters) and a non-empty URL (up to 2048 characters) via the link input form, THE Quick_Links SHALL add a new Link and persist it to LocalStorage.",
"2. IF the user submits a link with an empty label, an empty URL, a label exceeding 100 characters, or a URL exceeding 2048 characters, THEN THE Quick_Links SHALL not add the Link and SHALL display an inline validation message.",
"3. IF the user submits a URL that does not begin with `"http://`" or `"https://`", THEN THE Quick_Links SHALL prepend `"https://`" to the URL before saving.",
"4. WHEN the user clicks a Link button, THE Dashboard SHALL open the corresponding URL in a new browser tab.",
"5. WHEN the user clicks the delete button on a Link, THE Quick_Links SHALL remove the Link from the panel and update LocalStorage.",
"6. WHEN the Dashboard loads and LocalStorage data for Quick_Links is valid and readable, THE Quick_Links SHALL restore all previously saved Links from LocalStorage.",
"7. IF LocalStorage data for Quick_Links is unreadable or corrupted on load, THEN THE Quick_Links SHALL initialize with an empty panel and not throw an unhandled error.",
"8. IF the user attempts to add a Link when 50 Links are already saved, THEN THE Quick_Links SHALL not add the new Link and SHALL display a validation message indicating the maximum limit has been reached.",
"",
"---",
"",
"### Requirement 6: Light and Dark Theme",
"",
"**User Story:** As a user, I want to switch between a light and dark visual theme, so that I can use the dashboard comfortably in different lighting conditions.",
"",
"#### Acceptance Criteria",
"",
"1. THE Dashboard SHALL provide a toggle control to switch between the `"light`" and `"dark`" Theme.",
"2. WHEN the user activates the theme toggle, THE Dashboard SHALL apply the selected Theme to all visible UI components (background, text, buttons, inputs, and widget containers) within 200ms and without a page reload.",
"3. WHEN the user activates the theme toggle, THE toggle control SHALL reflect the currently active Theme (e.g., label or icon updates to indicate the active state).",
"4. WHEN a Theme is selected, THE Dashboard SHALL persist the Theme preference to LocalStorage.",
"5. WHEN the Dashboard loads, THE Dashboard SHALL restore the previously saved Theme from LocalStorage.",
"6. IF no Theme preference has been saved, THEN THE Dashboard SHALL apply the `"light`" Theme by default.",
"7. IF LocalStorage is unavailable when saving the Theme preference, THEN THE Dashboard SHALL still apply the selected Theme for the current session without throwing an unhandled error.",
"",
"---",
"",
"### Requirement 7: Data Persistence and Initialization",
"",
"**User Story:** As a user, I want my data to be saved automatically so that my tasks, links, name, and settings are still available when I reopen the dashboard.",
"",
"#### Acceptance Criteria",
"",
"1. THE Dashboard SHALL use the browser LocalStorage API as the sole data persistence mechanism.",
"2. WHEN the Dashboard loads for the first time with no existing LocalStorage data, THE Dashboard SHALL initialize with an empty Task_List, an empty Quick_Links panel, the placeholder User_Name `"there`", the default Pomodoro_Duration of 25 minutes, and the `"light`" Theme.",
"3. WHEN any user data changes (Task added, edited, or deleted; Link added or deleted; User_Name updated; Pomodoro_Duration updated; Theme changed), THE Dashboard SHALL write the updated data to LocalStorage immediately and synchronously before returning control to the user.",
"4. THE Dashboard SHALL render and operate all features fully without a backend server or network connection, including loading saved data, updating the timer, managing tasks, and switching themes.",
"5. IF a LocalStorage write operation fails (e.g., storage quota exceeded), THEN THE Dashboard SHALL display a non-blocking warning message to the user and continue operating for the current session without throwing an unhandled error.",
"6. IF LocalStorage data for any key is unrecognizable or unparseable on load, THEN THE Dashboard SHALL silently discard that key's data, initialize the corresponding feature with its default value, and not throw an unhandled error."
)

$lines | Set-Content -Path $filePath -Encoding UTF8
Write-Host "Done. Lines written: $($lines.Count)"
